openapi: 3.0.0
info:
  title: RAG Chatbot API for Physical AI & Humanoid Robotics Book
  description: API for the RAG (Retrieval Augmented Generation) system that powers the interactive chatbot in the Physical AI & Humanoid Robotics textbook
  version: 1.0.0
servers:
  - url: https://api.physical-ai-book.com
    description: Production server
  - url: https://staging.api.physical-ai-book.com
    description: Staging server

paths:
  /api/v1/query:
    post:
      summary: Submit a query to the RAG system
      description: Submit a user query along with optional selected text context to get a response based on the book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the RAG system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/documents:
    get:
      summary: List all available documents
      description: Retrieve a list of all documents (chapters) available in the RAG system
      responses:
        '200':
          description: List of available documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentSummary'
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/documents/{documentId}:
    get:
      summary: Get document details
      description: Retrieve details about a specific document by ID
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the document
      responses:
        '200':
          description: Document details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/health:
    get:
      summary: Health check
      description: Check the health status of the RAG API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's query text
          example: "Explain how ROS 2 nodes communicate with each other"
        selected_text:
          type: string
          description: Optional text selected by the user on the page
          example: "ROS 2 nodes communicate through topics, services, and actions"
        context:
          type: object
          description: Additional context for the query
          properties:
            page_url:
              type: string
              description: URL of the page where query was made
            session_id:
              type: string
              description: Session identifier for the conversation
        user_id:
          type: string
          description: Optional user identifier
          example: "user-12345"

    QueryResponse:
      type: object
      required:
        - response
        - sources
      properties:
        response:
          type: string
          description: The AI-generated response to the query
          example: "ROS 2 nodes communicate through a publish-subscribe model using topics for asynchronous communication..."
        sources:
          type: array
          description: List of source documents used to generate the response
          items:
            $ref: '#/components/schemas/SourceDocument'
        confidence:
          type: number
          format: float
          description: Confidence score of the response (0-1)
          minimum: 0
          maximum: 1
          example: 0.85
        query_id:
          type: string
          description: Unique identifier for this query
          example: "query-67890"

    SourceDocument:
      type: object
      properties:
        document_id:
          type: string
          description: Unique identifier of the source document
          example: "doc-001"
        title:
          type: string
          description: Title of the source document
          example: "Chapter 1: The Robotic Nervous System (ROS 2)"
        chapter_number:
          type: integer
          description: Chapter number in the book
          example: 1
        url:
          type: string
          description: URL to the source document
          example: "/docs/chapter-1-ros2"

    DocumentSummary:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the document
          example: "doc-001"
        title:
          type: string
          description: Title of the document
          example: "Chapter 1: The Robotic Nervous System (ROS 2)"
        chapter_number:
          type: integer
          description: Chapter number in the book
          example: 1
        module:
          type: string
          description: Module identifier
          example: "ROS2"
        created_at:
          type: string
          format: date-time
          description: Creation timestamp

    Document:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the document
          example: "doc-001"
        title:
          type: string
          description: Title of the document
          example: "Chapter 1: The Robotic Nervous System (ROS 2)"
        content:
          type: string
          description: Full content of the document
          example: "# The Robotic Nervous System\n\nROS 2 provides the communication framework for robotic systems..."
        chapter_number:
          type: integer
          description: Chapter number in the book
          example: 1
        module:
          type: string
          description: Module identifier
          example: "ROS2"
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    HealthStatus:
      type: object
      properties:
        status:
          type: string
          description: Health status of the service
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the health check
        version:
          type: string
          description: API version
          example: "1.0.0"

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication