openapi: 3.0.3
info:
  title: BiblioChat API
  description: API for the BiblioChat RAG-based book reader application
  version: 1.0.0
  contact:
    name: BiblioChat Development Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.bibliochat.example.com
    description: Production server

paths:
  /api/chat:
    post:
      summary: Process user query with book context
      description: |
        Handles user queries with dual-mode logic:
        - Selection Mode: If selection_context is provided, bypasses vector search and sends text directly to AI
        - Global Mode: If selection_context is null, performs vector search in Qdrant and sends results to AI
      operationId: processChatQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            example:
              query: "What is the main concept discussed in this section?"
              selection_context: "This is a sample book content for testing the BiblioChat backend. The AI assistant will be able to answer questions about this text content using the RAG system."
              session_id: "session-12345-abcde"
      responses:
        '200':
          description: Successful response from the AI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
              example:
                response: "The main concept discussed in the provided text is the BiblioChat backend system, which uses a RAG (Retrieval Augmented Generation) approach to answer questions about book content."
                sources: ["Sample book content chunk 1", "Sample book content chunk 2"]
        '400':
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Chat

  /api/health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: getHealth
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-12-18T10:30:00Z"
      tags:
        - Health

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - query
        - session_id
      properties:
        query:
          type: string
          description: The user's question or query about the book
          example: "Explain the concept of RAG in this context"
          minLength: 1
          maxLength: 10000
        selection_context:
          type: string
          description: The text selected by the user (null for global search)
          example: "This is a sample book content for testing the BiblioChat backend."
          nullable: true
        session_id:
          type: string
          description: Unique identifier for the chat session
          example: "session-12345-abcde"
          pattern: "^[a-zA-Z0-9-_]+$"
          minLength: 1
          maxLength: 255
      example:
        query: "What is the main concept discussed in this section?"
        selection_context: "This is a sample book content for testing the BiblioChat backend."
        session_id: "session-12345-abcde"

    ChatResponse:
      type: object
      required:
        - response
        - sources
      properties:
        response:
          type: string
          description: The AI-generated response to the user's query
          example: "The main concept discussed in the provided text is the BiblioChat backend system, which uses a RAG (Retrieval Augmented Generation) approach to answer questions about book content."
        sources:
          type: array
          description: List of sources used in the AI response (empty for selection mode)
          items:
            type: string
          example: ["Sample book content chunk 1", "Sample book content chunk 2"]

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INTERNAL_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "An internal error occurred while processing the request"

tags:
  - name: Chat
    description: Endpoints related to chat functionality
  - name: Health
    description: Health check and monitoring endpoints